---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizzbackend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pizzbackend
    spec:
      containers:
      - name: pizzbackend
        image: netjonin/pizzbackend:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
      app: pizzbackend
---
apiVersion: v1
kind: Service
metadata:
  name: pizzbackend
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: pizzbackend